{% set name = "pastel" %}
{% set version = "0.8.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 481da9fb7d2f6e6b1a08faf11fa10363172dc40fd47848f096ae21209f805a75

build:
  noarch: generic
  number: 2
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem 
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.5,<2.7
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-tty-color >=0.5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Terminal output styling with intuitive and clean API that does not monkey patch String class.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/piotrmurach/pastel

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
