travis:
  secure:
    BINSTAR_TOKEN: oDcxwbBUVTT8j2MKbPsZQ5bfsH8hXa0rf1BsaVvDMrELEvJXb0aA26Hhrb14Igweuf7vZL+Nqj5F47qK8FdMtxVNu29Hp3MPWjXaWameJUOWUBEJW8urs1NfzNKnGbbqxo+nP2xOpQEHfFxT3Svsz2epnBIcMXeNX377xDVXjkBuS/uFBhh9NPgtru7IRMjmmjN03HXOAkiLi1PfTRi94QOOYQvg6ipxz86iBKnVRSGch8cD+RqsPTzaEtaU9lpdd49SY9GhZodPHCs+vmDy0r5gHllM3yycni007V4biw66VSI7FU76T9etIWGWVjzGDV4CNLG2JZbbiczd/qM+exaGPXlzsPEW1WKCBB6+KtzRJP1czR33nBNqFrFqY8+R50D1OsVEPY0OxjzX9pwOXV3fDqcE0exPjlE5Bt5KJSqihvliuNBTlLAR5JZWcElfsvA/81o+EWeQoFFpXJ1VDzjdZ4KEuTJWD523kXtPRQ3kYR7ql5TyWvuOx8UIt9/e3qF4MHHn/daEOgyJKTVAeMWFb+RFwL/v3nJydU+BB8pvK7fja0HAL/r1yBUHAap24Mby6h7FfeQzs0QOHuzozHCX4j0TgirdylgfzfWcUrWL5OCOw+U3T4+8y0ChTinVBhTI1sSqvcmUp2QNHk05hQLz9x5x9vMRGfNyvRQN//w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
